### ISSUE TITLE
Exception in GroupUtility

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#140]
`Caused by: java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:319)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:718)
	at java.base/java.time.LocalDate.of(LocalDate.java:272)
	at deployment.seerdms_ut.war//com.imsweb.mph.mpgroups.GroupUtility.daysInBetween(GroupUtility.java:353)
	at deployment.seerdms_ut.war//com.imsweb.mph.mpgroups.GroupUtility.verifyDaysApart(GroupUtility.java:321)
	at deployment.seerdms_ut.war//com.imsweb.mph.mpgroups.Mp2004SolidMalignantGroup$3.apply(Mp2004SolidMalignantGroup.java:56)
	at deployment.seerdms_ut.war//com.imsweb.mph.MphUtils.computePrimaries(MphUtils.java:261)`

**Comment by depryf** [comment]
@bekeles I don't want this bug to sit for too long. Do you think you will have time to work on a fix soon?

**Comment by depryf** [comment]
What's your timeline for the 2024 release? If it's weeks and not months, then I am fine waiting.

**Comment by bekeles** [comment]
next week or a week after.

**Comment by depryf** [comment]
Good enough, although you are welcome to make the changes before that if you can.  But I agree we don't need to push a release.
